export   const nodes = [
    {
      id: "1",
      parent_id: null,
      data: { label: "Frontend" },
      position: { x: 218, y: -50 },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "2",
      parent_id: null,
      data: { label: "Internet" },
      position: { x: 242, y: 50 },
      type: "Internet",
    },
    {
      id: "3",
      data: { label: "How does the internet work?" },
      position: { x: 450, y: -40 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "4",
      data: { label: "What is HTTP?" },
      position: { x: 450, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "5",
      data: { label: "What is Domain Name?" },
      position: { x: 450, y: 80 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "6",
      data: { label: "What is hosting?" },
      position: { x: 450, y: 130 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "7",
      data: { label: "DNS and how it works?" },
      position: { x: 450, y: 180 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "8",
      data: { label: "Browsers and how they work?" },
      position: { x: 450, y: 230 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "9",
      parent_id: null,
      data: { label: "HTML" },
      position: { x: -50, y: 230 },
      type: "HTML",
    },
    {
      id: "10",
      parent_id: null,
      data: { label: "SEO Basics" },
      position: { x: -75, y: 170 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "11",
      parent_id: null,
      data: { label: "Accessibility" },
      position: { x: -75, y: 125 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "12",
      parent_id: null,
      data: { label: "Forms and Validations" },
      position: { x: -75, y: 80 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "13",
      parent_id: null,
      data: { label: "Writing Semantic HTML" },
      position: { x: -75, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "14",
      parent_id: null,
      data: { label: "Learn the basics" },
      position: { x: -75, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "15",
      parent_id: null,
      data: { label: "CSS" },
      position: { x: 160, y: 320 },
      type: "CSS",
    },
    {
      id: "16",
      parent_id: null,
      data: { label: "Learn the basics" },
      position: { x: 280, y: 280 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "17",
      parent_id: null,
      data: { label: "Making Layout" },
      position: { x: 280, y: 325 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "18",
      parent_id: null,
      data: { label: "Responsive Design" },
      position: { x: 280, y: 370 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "19",
      parent_id: null,
      data: { label: "JavaScript" },
      position: { x: 138.5, y: 480 },
      type: "JS",
    },
    {
      id: "20",
      parent_id: null,
      data: { label: "Learn the basics" },
      position: { x: -50, y: 440 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "21",
      parent_id: null,
      data: { label: "Learn DOM Manipulation" },
      position: { x: -50, y: 490 },
      style: { background: "#FFEEBA", color: "black", padding: "6px" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "22",
      parent_id: null,
      data: { label: "Fetch API / Ajax (XHR)" },
      position: { x: -50, y: 530 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "23",
      parent_id: null,
      data: { label: "Version Control Systems" },
      position: { x: 370, y: 480 },
      type: "VCS",
    },
    {
      id: "24",
      parent_id: null,
      data: { label: "Git" },
      position: { x: 406.5, y: 580 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "25",
      parent_id: null,
      data: { label: "VCS Hosting" },
      position: { x: 670, y: 480 },
      type: "VCS_Hosting",
    },
    {
      id: "26",
      parent_id: null,
      data: { label: "Bitbucket" },
      position: { x: 667, y: 390 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "27",
      parent_id: null,
      data: { label: "GitLab" },
      position: { x: 667, y: 340 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "28",
      parent_id: null,
      data: { label: "GitHub" },
      position: { x: 667, y: 290 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "29",
      parent_id: null,
      data: { label: "Package Manager" },
      position: { x: 450, y: 700 },
      type: "PM",
    },
    {
      id: "30",
      parent_id: null,
      data: { label: "npm" },
      position: { x: 230, y: 662 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "31",
      parent_id: null,
      data: { label: "pnpm" },
      position: { x: 230, y: 706 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "32",
      parent_id: null,
      data: { label: "yarn" },
      position: { x: 230, y: 750 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "33",
      parent_id: null,
      data: {
        label:
          "We've trimmed down the CSS part for the sake of brevity. You should read about CSS-in-JS, CSS Modules and Styled Components. Alss worth looking at are Pande CSS, Shadcn UI, Mantine and more.",
      },
      position: { x: -120, y: 650 },
      type: "TEXT",
    },
    {
      id: "34",
      parent_id: null,
      data: { label: "Pick a Framework" },
      position: { x: 450.5, y: 896 },
      type: "PaF",
    },
    {
      id: "35",
      parent_id: null,
      data: { label: "React" },
      position: { x: 720, y: 780 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "36",
      parent_id: null,
      data: { label: "Vue.js" },
      position: { x: 720, y: 830 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "37",
      parent_id: null,
      data: { label: "Angular" },
      position: { x: 720, y: 880 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "38",
      parent_id: null,
      data: { label: "Svelte" },
      position: { x: 720, y: 930 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "39",
      parent_id: null,
      data: { label: "Solid.js" },
      position: { x: 720, y: 980 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "40",
      parent_id: null,
      data: { label: "Qwik" },
      position: { x: 720, y: 1030 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "41",
      parent_id: null,
      data: { label: "Writing CSS" },
      position: { x: 101.5, y: 896 },
      type: "WCSS",
    },
    {
      id: "42",
      parent_id: null,
      data: { label: "Tailwind" },
      position: { x: -120, y: 902 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "43",
      parent_id: null,
      data: { label: "CSS Architecture" },
      position: { x: 85, y: 1090 },
      type: "CSSArch",
    },
    {
      id: "44",
      parent_id: null,
      data: { label: "BEM" },
      position: { x: -120, y: 1096 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "45",
      parent_id: null,
      data: { label: "CSS Preprocessors" },
      position: { x: 385, y: 1090 },
      type: "CSSPre",
    },
    {
      id: "46",
      parent_id: null,
      data: { label: "Sass" },
      position: { x: 320, y: 1200 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "47",
      parent_id: null,
      data: { label: "PostCSS" },
      position: { x: 480, y: 1200 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "48",
      parent_id: null,
      data: { label: "Build Tools" },
      position: { x: 750, y: 1360 },
      type: "BTools",
    },
    {
      id: "49",
      parent_id: null,
      data: { label: "Linters and Formatters" },
      position: { x: 400, y: 1320 },
      type: "LaF",
    },
    {
      id: "50",
      parent_id: null,
      data: { label: "Prettier" },
      position: { x: 340, y: 1250 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "51",
      parent_id: null,
      data: { label: "ESLint" },
      position: { x: 510, y: 1250 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "52",
      parent_id: null,
      data: { label: "Module Bundlers" },
      position: { x: 400, y: 1394 },
      type: "ModuleB",
    },
    {
      id: "53",
      parent_id: null,
      data: { label: "Vite" },
      position: { x: 180, y: 1300 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "54",
      parent_id: null,
      data: { label: "esbuild" },
      position: { x: 260, y: 1350 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "55",
      parent_id: null,
      data: { label: "SWC" },
      position: { x: 180, y: 1350 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "56",
      parent_id: null,
      data: { label: "Webpack" },
      position: { x: 180, y: 1400 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "57",
      parent_id: null,
      data: { label: "Rollup" },
      position: { x: 180, y: 1450 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "58",
      parent_id: null,
      data: { label: "Parcel" },
      position: { x: 180, y: 1500 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "59",
      parent_id: null,
      data: { label: "Testing" },
      position: { x: 762, y: 1580 },
      type: "Test",
    },
    {
      id: "60",
      parent_id: null,
      data: { label: "Jest" },
      position: { x: 550, y: 1550 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "61",
      parent_id: null,
      data: { label: "Vitest" },
      position: { x: 398, y: 1550 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "62",
      parent_id: null,
      data: { label: "Playwright" },
      position: { x: 743, y: 1680 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "63",
      parent_id: null,
      data: { label: "Cypress" },
      position: { x: 743, y: 1722 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "64",
      parent_id: null,
      data: { label: "Authentication Strategies" },
      position: { x: 300, y: 1680 },
      type: "Auth",
    },
    {
      id: "65",
      parent_id: null,
      data: { label: "Web Security Basics" },
      position: { x: -80, y: 1620 },
      type: "WSB",
    },
    {
      id: "66",
      parent_id: null,
      data: { label: "OWASP Security Risks" },
      position: { x: -58, y: 1500 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "67",
      parent_id: null,
      data: { label: "Content Security Policy" },
      position: { x: -58, y: 1455 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "68",
      parent_id: null,
      data: { label: "CORS" },
      position: { x: -58, y: 1410 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "69",
      parent_id: null,
      data: { label: "HTTPS" },
      position: { x: 22, y: 1410 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "70",
      parent_id: null,
      data: { label: "Web Components" },
      position: { x: -73, y: 1850 },
      type: "WebC",
    },
    {
      id: "71",
      parent_id: null,
      data: { label: "HTML Templates" },
      position: { x: -58, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "72",
      parent_id: null,
      data: { label: "Custom Elements" },
      position: { x: -58, y: 2000 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "73",
      parent_id: null,
      data: { label: "Shadow DOM" },
      position: { x: -58, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "74",
      parent_id: null,
      data: { label: "Type Checkers" },
      position: { x: 250, y: 1850 },
      type: "TypeC",
    },
    {
      id: "75",
      parent_id: null,
      data: { label: "TypeScript" },
      position: { x: 254, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "76",
      parent_id: null,
      data: { label: "SSR" },
      position: { x: 500, y: 2020 },
      type: "SSR",
    },
    {
      id: "77",
      parent_id: null,
      data: { label: "React" },
      position: { x: 680, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Right,
    },
    {
      id: "78",
      parent_id: null,
      data: { label: "Next.js" },
      position: { x: 880, y: 1900 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "79",
      parent_id: null,
      data: { label: "Astro" },
      position: { x: 880, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "80",
      parent_id: null,
      data: { label: "react-router" },
      position: { x: 880, y: 2000 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "81",
      parent_id: null,
      data: { label: "Angular" },
      position: { x: 680, y: 2000 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "82",
      parent_id: null,
      data: { label: "Vue.js" },
      position: { x: 680, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Right,
    },
    {
      id: "83",
      parent_id: null,
      data: { label: "Nuxt.js" },
      position: { x: 860, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "84",
      parent_id: null,
      data: { label: "Svelte" },
      position: { x: 680, y: 2100 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Right,
    },
    {
      id: "85",
      parent_id: null,
      data: { label: "Svelte Kit" },
      position: { x: 860, y: 2100 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "86",
      parent_id: null,
      data: { label: "GraphQL" },
      position: { x: 251, y: 2200 },
      type: "GraphQL",
    },
    {
      id: "87",
      parent_id: null,
      data: { label: "Relay Modern" },
      position: { x: 237, y: 2100 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "88",
      parent_id: null,
      data: { label: "Apollo" },
      position: { x: 237, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "89",
      parent_id: null,
      data: { label: "PWAs" },
      position: { x: 261, y: 2360 },
      type: "PWAs",
    },
    {
      id: "90",
      parent_id: null,
      data: { label: "box" },
      position: { x: 0, y: 2120 },
      type: "box",
    },
    {
      id: "91",
      parent_id: null,
      data: { label: "Using DevTools" },
      position: { x: 10, y: 2340 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "92",
      parent_id: null,
      data: { label: "Using Lighthouse" },
      position: { x: 10, y: 2290 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "93",
      parent_id: null,
      data: { label: "Performance Metrics" },
      position: { x: 10, y: 2240 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "94",
      parent_id: null,
      data: { label: "RAIL Model" },
      position: { x: 10, y: 2190 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "95",
      parent_id: null,
      data: { label: "PRPL Pattern" },
      position: { x: 10, y: 2140 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "96",
      parent_id: null,
      data: { label: "box2" },
      position: { x: 0, y: 2455 },
      type: "box2",
    },
    {
      id: "97",
      parent_id: null,
      data: { label: "Credentials" },
      position: { x: 10, y: 2875 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "98",
      parent_id: null,
      data: { label: "Payments" },
      position: { x: 10, y: 2825 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "99",
      parent_id: null,
      data: { label: "Device Orientation" },
      position: { x: 10, y: 2775 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "100",
      parent_id: null,
      data: { label: "Notifications" },
      position: { x: 10, y: 2725 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "101",
      parent_id: null,
      data: { label: "Location" },
      position: { x: 10, y: 2675 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "102",
      parent_id: null,
      data: { label: "Service Workers" },
      position: { x: 10, y: 2625 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "103",
      parent_id: null,
      data: { label: "Server Sent Events" },
      position: { x: 10, y: 2575 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "104",
      parent_id: null,
      data: { label: "Web Socket" },
      position: { x: 10, y: 2525 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "105",
      parent_id: null,
      data: { label: "Storage" },
      position: { x: 10, y: 2475 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "106",
      parent_id: null,
      data: { label: "Performance Best Practices" },
      position: { x: 240, y: 2500 },
      type: "PBP",
    },
    {
      id: "107",
      parent_id: null,
      data: { label: "Static Site Generators" },
      position: { x: 560, y: 2360 },
      type: "SSG",
    },
    {
      id: "108",
      parent_id: null,
      data: { label: "Eleventy" },
      position: { x: 588, y: 2270 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "109",
      parent_id: null,
      data: { label: "Vuepress" },
      position: { x: 588, y: 2220 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "110",
      parent_id: null,
      data: { label: "Next.js" },
      position: { x: 588, y: 2170 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "111",
      parent_id: null,
      data: { label: "Astro" },
      position: { x: 668, y: 2170 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "112",
      parent_id: null,
      data: { label: "Nuxt.js" },
      position: { x: 588, y: 2480 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "113",
      parent_id: null,
      data: { label: "Mobile Apps" },
      position: { x: 880, y: 2360 },
      type: "Mobile",
    },
    {
      id: "114",
      parent_id: null,
      data: { label: "Ionic" },
      position: { x: 877, y: 2270 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "115",
      parent_id: null,
      data: { label: "Flutter" },
      position: { x: 877, y: 2220 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "116",
      parent_id: null,
      data: { label: "React Native" },
      position: { x: 877, y: 2170 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "117",
      parent_id: null,
      data: { label: "Desktop Apps" },
      position: { x: 580, y: 2650 },
      type: "Desktop",
    },
    {
      id: "118",
      parent_id: null,
      data: { label: "Electron" },
      position: { x: 380, y: 2605 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "119",
      parent_id: null,
      data: { label: "Tauri" },
      position: { x: 380, y: 2655 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "120",
      parent_id: null,
      data: { label: "Flutter" },
      position: { x: 380, y: 2705 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
  ];

export const edges = [
  {
    id: "e1-2",
    source: "1",
    target: "2",
    animated: true,
    type: "smoothstep",
    targetHandle: "top",
  },
  {
    id: "e2-3",
    source: "2",
    target: "3",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-6",
    source: "2",
    target: "6",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-7",
    source: "2",
    target: "7",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-8",
    source: "2",
    target: "8",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-9",
    source: "2",
    target: "9",
    type: "bezier",
  },
  {
    id: "e2-10",
    source: "9",
    target: "10",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-11",
    source: "9",
    target: "11",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-12",
    source: "9",
    target: "12",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-13",
    source: "9",
    target: "13",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-14",
    source: "9",
    target: "14",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e9-15",
    source: "9",
    target: "15",
    type: "bezier",
    sourceHandle: "right2",
    targetHandle: "left",
  },
  {
    id: "e15-16",
    source: "15",
    target: "16",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "e15-17",
    source: "15",
    target: "17",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "e15-18",
    source: "15",
    target: "18",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "e15-19",
    source: "15",
    target: "19",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "e19-20",
    source: "19",
    target: "20",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "e19-21",
    source: "19",
    target: "21",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "e19-22",
    source: "19",
    target: "22",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "e19-23",
    source: "19",
    target: "23",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e23-24",
    source: "23",
    target: "24",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "e23-25",
    source: "23",
    target: "25",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "25-26",
    source: "25",
    target: "26",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "25-27",
    source: "25",
    target: "27",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "25-28",
    source: "25",
    target: "28",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "25-29",
    source: "25",
    target: "29",
    animated: false,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "29-30",
    source: "29",
    target: "30",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "29-31",
    source: "29",
    target: "31",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "29-32",
    source: "29",
    target: "32",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "29-34",
    source: "29",
    target: "34",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "34-35",
    source: "34",
    target: "35",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-36",
    source: "34",
    target: "36",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-37",
    source: "34",
    target: "37",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-38",
    source: "34",
    target: "38",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-39",
    source: "34",
    target: "39",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-40",
    source: "34",
    target: "40",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-41",
    source: "34",
    target: "41",
    animated: false,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "41-42",
    source: "41",
    target: "42",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "41-43",
    source: "41",
    target: "43",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "43-44",
    source: "43",
    target: "44",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "43-45",
    source: "43",
    target: "45",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "45-46",
    source: "45",
    target: "46",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "45-47",
    source: "45",
    target: "47",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom2",
  },
  {
    id: "45-48",
    source: "45",
    target: "48",
    animated: false,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "48-49",
    source: "48",
    target: "49",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "49-50",
    source: "49",
    target: "50",
    animated: true,
    type: "bezier",
    sourceHandle: "top",
  },
  {
    id: "49-51",
    source: "49",
    target: "51",
    animated: true,
    type: "bezier",
    sourceHandle: "top2",
  },
  {
    id: "48-52",
    source: "48",
    target: "52",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "52-53",
    source: "52",
    target: "53",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-54",
    source: "52",
    target: "54",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-56",
    source: "52",
    target: "56",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-57",
    source: "52",
    target: "57",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-58",
    source: "52",
    target: "58",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "48-59",
    source: "48",
    target: "59",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "59-60",
    source: "59",
    target: "60",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "59-63",
    source: "59",
    target: "63",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "59-64",
    source: "59",
    target: "64",
    animated: false,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "64-65",
    source: "64",
    target: "65",
    animated: false,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "65-66",
    source: "65",
    target: "66",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "65-67",
    source: "65",
    target: "67",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "65-70",
    source: "65",
    target: "70",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "70-73",
    source: "70",
    target: "73",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "70-74",
    source: "70",
    target: "74",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "74-75",
    source: "74",
    target: "75",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "74-76",
    source: "74",
    target: "76",
    animated: false,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "76-77",
    source: "76",
    target: "77",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "77-78",
    source: "77",
    target: "78",
    animated: true,
    type: "bezier",
  },
  {
    id: "77-79",
    source: "77",
    target: "79",
    animated: true,
    type: "bezier",
  },
  {
    id: "77-80",
    source: "77",
    target: "80",
    animated: true,
    type: "bezier",
  },
  {
    id: "76-81",
    source: "76",
    target: "81",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "76-82",
    source: "76",
    target: "82",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "82-83",
    source: "82",
    target: "83",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "76-84",
    source: "76",
    target: "84",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "84-85",
    source: "84",
    target: "85",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "76-86",
    source: "76",
    target: "86",
    animated: false,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "86-88",
    source: "86",
    target: "88",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "86-89",
    source: "86",
    target: "89",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "89-90",
    source: "89",
    target: "90",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "89-96",
    source: "89",
    target: "96",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "89-106",
    source: "89",
    target: "106",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "89-107",
    source: "89",
    target: "107",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "107-108",
    source: "107",
    target: "108",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "107-112",
    source: "107",
    target: "112",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "107-113",
    source: "107",
    target: "113",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "113-116",
    source: "113",
    target: "116",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "113-117",
    source: "113",
    target: "117",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "117-118",
    source: "117",
    target: "118",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "117-119",
    source: "117",
    target: "119",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "117-120",
    source: "117",
    target: "120",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
];

  const nodes2 = [
    {
      id: "1",
      parent_id: null,
      data: { label: "Frontend" },
      position: { x: 218, y: -50 },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "2",
      parent_id: null,
      data: { label: "Internet" },
      position: { x: 242, y: 50 },
      type: "Internet",
    },
    {
      id: "3",
      data: { label: "How does the internet work?" },
      position: { x: 450, y: -40 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "4",
      data: { label: "What is HTTP?" },
      position: { x: 450, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "5",
      data: { label: "What is Domain Name?" },
      position: { x: 450, y: 80 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "6",
      data: { label: "What is hosting?" },
      position: { x: 450, y: 130 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "7",
      data: { label: "DNS and how it works?" },
      position: { x: 450, y: 180 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "8",
      data: { label: "Browsers and how they work?" },
      position: { x: 450, y: 230 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "9",
      parent_id: null,
      data: { label: "Pick a Language" },
      position: { x: 45, y: 180 },
      type: "PaL",
    },
    {
      id: "10",
      data: { label: "Rust" },
      position: { x: -150, y: 185 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "11",
      data: { label: "PHP" },
      position: { x: -300, y: 185 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "12",
      data: { label: "C#" },
      position: { x: -150, y: 145 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "13",
      data: { label: "Java" },
      position: { x: -300, y: 145 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "14",
      data: { label: "Ruby" },
      position: { x: -150, y: 105 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "15",
      data: { label: "Python" },
      position: { x: -300, y: 105 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "16",
      parent_id: null,
      data: { label: "Go" },
      position: { x: -150, y: 65 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "17",
      parent_id: null,
      data: { label: "JavaScript" },
      position: { x: -300, y: 65 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "18",
      parent_id: null,
      data: { label: "Pattern HMVC/DDD/MMVC" },
      position: { x: -225, y: 5 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "19",
      parent_id: null,
      data: { label: "Guard Clause" },
      position: { x: -225, y: -35 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "20",
      parent_id: null,
      data: { label: "Version Control Systems" },
      position: { x: 175, y: 380 },
      type: "VCS",
    },
    {
      id: "21",
      parent_id: null,
      data: { label: "Git" },
      position: { x: 203, y: 300 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "22",
      parent_id: null,
      data: { label: "Repo Hosting Services" },
      position: { x: -154, y: 440 },
      type: "RPS",
    },
    {
      id: "23",
      parent_id: null,
      data: { label: "GitLab" },
      position: { x: -133, y: 370 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "24",
      parent_id: null,
      data: { label: "GitHub" },
      position: { x: -133, y: 320 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "25",
      parent_id: null,
      data: { label: "Bitbucket" },
      position: { x: -133, y: 530 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "26",
      parent_id: null,
      data: { label: "Relational Databases" },
      position: { x: 200, y: 590 },
      type: "RDatabase",
    },
    {
      id: "27",
      parent_id: null,
      data: { label: "PostgreSQL" },
      position: { x: 218, y: 510 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "28",
      parent_id: null,
      data: { label: "MySQL" },
      position: { x: 480, y: 450 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "29",
      parent_id: null,
      data: { label: "MariaDB" },
      position: { x: 480, y: 500 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "30",
      parent_id: null,
      data: { label: "MS SQL" },
      position: { x: 480, y: 550 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "31",
      parent_id: null,
      data: { label: "Oracle" },
      position: { x: 480, y: 600 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "32",
      parent_id: null,
      data: { label: "SQLite" },
      position: { x: 480, y: 650 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "33",
      parent_id: null,
      data: { label: "Learn about APIs" },
      position: { x: 213.3, y: 840 },
      type: "LearnAPIs",
    },
    {
      id: "34",
      parent_id: null,
      data: { label: "Open API Specs" },
      position: { x: 120, y: 750 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "35",
      parent_id: null,
      data: { label: "HATEOAS" },
      position: { x: 120, y: 710 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "36",
      parent_id: null,
      data: { label: "Authentication" },
      position: { x: 480, y: 840 },
      type: "Auth",
    },
    {
      id: "37",
      parent_id: null,
      data: { label: "JWT" },
      position: { x: 490, y: 900 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "38",
      parent_id: null,
      data: { label: "OAuth" },
      position: { x: 626, y: 900 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "39",
      parent_id: null,
      data: { label: "Basic Authentication" },
      position: { x: 555, y: 940 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "40",
      parent_id: null,
      data: { label: "Token Authentication" },
      position: { x: 555, y: 985 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "41",
      parent_id: null,
      data: { label: "Cookie Based Auth" },
      position: { x: 555, y: 1030 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "42",
      parent_id: null,
      data: { label: "OpenID" },
      position: { x: 626, y: 1075 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "43",
      parent_id: null,
      data: { label: "SAML" },
      position: { x: 490, y: 1075 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "44",
      parent_id: null,
      data: { label: "REST" },
      position: { x: 218, y: 925 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "45",
      parent_id: null,
      data: { label: "JSON APIs" },
      position: { x: 218, y: 970 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "46",
      parent_id: null,
      data: { label: "SOAP" },
      position: { x: 150, y: 1015 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "47",
      parent_id: null,
      data: { label: "gRPC" },
      position: { x: 285, y: 1015 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "48",
      parent_id: null,
      data: { label: "GraphQL" },
      position: { x: 218, y: 1060 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "49",
      parent_id: null,
      data: { label: "Caching" },
      position: { x: -50, y: 840 },
      type: "Caching",
    },
    {
      id: "50",
      parent_id: null,
      data: { label: "Server Side" },
      position: { x: -280, y: 846 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Right,
    },
    {
      id: "51",
      parent_id: null,
      data: { label: "CDN" },
      position: { x: -280, y: 886 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "52",
      parent_id: null,
      data: { label: "Client Side" },
      position: { x: -280, y: 926 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "53",
      parent_id: null,
      data: { label: "Memcached" },
      position: { x: -280, y: 750 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "54",
      parent_id: null,
      data: { label: "Redis" },
      position: { x: -280, y: 700 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "55",
      parent_id: null,
      data: { label: "Web Security" },
      position: { x: -65, y: 1200 },
      type: "WS",
    },
    {
      id: "56",
      parent_id: null,
      data: { label: "MD5" },
      position: { x: -280, y: 1100 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "57",
      parent_id: null,
      data: { label: "SHA" },
      position: { x: -280, y: 1150 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "58",
      parent_id: null,
      data: { label: "scrypt" },
      position: { x: -280, y: 1200 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "59",
      parent_id: null,
      data: { label: "bcrypt" },
      position: { x: -280, y: 1250 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "60",
      parent_id: null,
      data: { label: "Testing" },
      position: { x: 200, y: 1200 },
      type: "Testing",
    },
    {
      id: "61",
      parent_id: null,
      data: { label: "Integration Testing" },
      position: { x: 360, y: 1150 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "62",
      parent_id: null,
      data: { label: "Unit Testing" },
      position: { x: 360, y: 1200 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "63",
      parent_id: null,
      data: { label: "Functional Testing" },
      position: { x: 360, y: 1250 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "64",
      parent_id: null,
      data: { label: "CI / CD" },
      position: { x: 200, y: 1350 },
      type: "CC",
    },
    {
      id: "65",
      parent_id: null,
      data: { label: "More about Databases" },
      position: { x: 150, y: 1550 },
      type: "MaD",
    },
    {
      id: "66",
      parent_id: null,
      data: { label: "ORMs" },
      position: { x: 480, y: 1350 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "67",
      parent_id: null,
      data: { label: "ACID" },
      position: { x: 480, y: 1400 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "68",
      parent_id: null,
      data: { label: "Transactions" },
      position: { x: 480, y: 1450 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "69",
      parent_id: null,
      data: { label: "N+1 Problem" },
      position: { x: 480, y: 1500 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "70",
      parent_id: null,
      data: { label: "Normalization" },
      position: { x: 480, y: 1550 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "71",
      parent_id: null,
      data: { label: "Failure Modes" },
      position: { x: 480, y: 1600 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "72",
      parent_id: null,
      data: { label: "Profiling Perfor." },
      position: { x: 480, y: 1650 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "73",
      parent_id: null,
      data: { label: "Migrations" },
      position: { x: 480, y: 1700 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "74",
      parent_id: null,
      data: { label: "box" },
      position: { x: -250, y: 1400 },
      type: "box",
    },
    {
      id: "75",
      parent_id: null,
      data: { label: "HTTPS" },
      position: { x: -240, y: 1420 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "76",
      parent_id: null,
      data: { label: "OWASP Risks" },
      position: { x: -92, y: 1420 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "77",
      parent_id: null,
      data: { label: "CORS" },
      position: { x: -240, y: 1470 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "78",
      parent_id: null,
      data: { label: "SSL/TLS" },
      position: { x: -92, y: 1470 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "79",
      parent_id: null,
      data: { label: "CSP" },
      position: { x: -240, y: 1520 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "80",
      parent_id: null,
      data: { label: "Server Security" },
      position: { x: -92, y: 1520 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "81",
      parent_id: null,
      data: { label: "API Security Best Practices" },
      position: { x: -235, y: 1570 },
      type: "APISec",
    },
    {
      id: "82",
      parent_id: null,
      data: { label: "Scaling Databases" },
      position: { x: 15, y: 1703.5 },
      type: "SD",
    },
    {
      id: "83",
      parent_id: null,
      data: { label: "Database Indexes" },
      position: { x: -210, y: 1710 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "84",
      parent_id: null,
      data: { label: "Data Replication" },
      position: { x: -210, y: 1760 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "85",
      parent_id: null,
      data: { label: "Sharding Strategies" },
      position: { x: -210, y: 1810 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "86",
      parent_id: null,
      data: { label: "CAP Thoerem" },
      position: { x: -210, y: 1860 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "87",
      parent_id: null,
      data: { label: "Software Design & Architecture" },
      position: { x: 125, y: 1830 },
      type: "SDA",
    },
    {
      id: "88",
      parent_id: null,
      data: { label: "Architectural Patterns" },
      position: { x: 510, y: 1830 },
      type: "AP",
    },
    {
      id: "89",
      parent_id: null,
      data: { label: "Monolithic Apps" },
      position: { x: 530, y: 1930 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "90",
      parent_id: null,
      data: { label: "Microservices" },
      position: { x: 530, y: 1980 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "91",
      parent_id: null,
      data: { label: "SOA" },
      position: { x: 530, y: 2030 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "92",
      parent_id: null,
      data: { label: "Serverless" },
      position: { x: 530, y: 2080 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "93",
      parent_id: null,
      data: { label: "Service Mesh" },
      position: { x: 530, y: 2130 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "94",
      parent_id: null,
      data: { label: "Twelve Factor Apps" },
      position: { x: 530, y: 2180 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "95",
      parent_id: null,
      data: { label: "Design and Development Principles" },
      position: { x: 112, y: 1950 },
      type: "DesignDevPrin",
    },
    {
      id: "96",
      parent_id: null,
      data: { label: "GOF Design Patterns" },
      position: { x: -150, y: 1956 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "97",
      parent_id: null,
      data: { label: "Domain Driven Design" },
      position: { x: -150, y: 2006 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "98",
      parent_id: null,
      data: { label: "Test Driven Development" },
      position: { x: -150, y: 2056 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "99",
      parent_id: null,
      data: { label: "CQRS" },
      position: { x: -150, y: 2122 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "100",
      parent_id: null,
      data: { label: "Event Sourcing" },
      position: { x: -150, y: 2170 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "101",
      parent_id: null,
      data: { label: "Containerization vs Virtualization" },
      position: { x: 119, y: 2250 },
      type: "CV",
    },
    {
      id: "102",
      parent_id: null,
      data: { label: "LXC" },
      position: { x: 82, y: 2170 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "103",
      parent_id: null,
      data: { label: "Docker" },
      position: { x: 82, y: 2128 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "104",
      parent_id: null,
      data: { label: "Kubernetes" },
      position: { x: -100, y: 2256.5 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "105",
      parent_id: null,
      data: { label: "Message Brokers" },
      position: { x: 480, y: 2400 },
      type: "MB",
    },
    {
      id: "106",
      parent_id: null,
      data: { label: "RabbitMQ" },
      position: { x: 500, y: 2465 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "107",
      parent_id: null,
      data: { label: "Kafka" },
      position: { x: 500, y: 2504 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "108",
      parent_id: null,
      data: { label: "Search Engines" },
      position: { x: 145, y: 2400 },
      type: "SE",
    },
    {
      id: "109",
      parent_id: null,
      data: { label: "Elasticsearch" },
      position: { x: 160, y: 2465 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "110",
      parent_id: null,
      data: { label: "Solr" },
      position: { x: 160, y: 2504 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "111",
      parent_id: null,
      data: { label: "Web Servers" },
      position: { x: -100, y: 2400 },
      type: "WebS",
    },
    {
      id: "112",
      parent_id: null,
      data: { label: "Nginx" },
      position: { x: -300, y: 2350 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "113",
      parent_id: null,
      data: { label: "Apache" },
      position: { x: -300, y: 2400 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "114",
      parent_id: null,
      data: { label: "Caddy" },
      position: { x: -300, y: 2450 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "115",
      parent_id: null,
      data: { label: "MS IIS" },
      position: { x: -300, y: 2500 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Right,
      targetPosition: Position.Right,
    },
    {
      id: "116",
      parent_id: null,
      data: { label: "Real-Time Data" },
      position: { x: 180, y: 2650 },
      type: "RTD",
    },
    {
      id: "117",
      parent_id: null,
      data: { label: "Server Sent Events" },
      position: { x: 400, y: 2656 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "118",
      parent_id: null,
      data: { label: "WebSocket" },
      position: { x: 400, y: 2706 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "119",
      parent_id: null,
      data: { label: "Long Polling" },
      position: { x: 400, y: 2756 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "120",
      parent_id: null,
      data: { label: "Short Polling" },
      position: { x: 400, y: 2806 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "121",
      parent_id: null,
      data: { label: "GraphQL" },
      position: { x: 200, y: 2750 },
      type: "GraphQL",
    },
    {
      id: "122",
      parent_id: null,
      data: { label: "NoSQL Databases" },
      position: { x: -40, y: 3000 },
      type: "NoSQL",
    },
    {
      id: "123",
      parent_id: null,
      data: { label: "Key-Value" },
      position: { x: -158, y: 2675 },
      type: "KV",
    },
    {
      id: "124",
      parent_id: null,
      data: { label: "Redis" },
      position: { x: -145, y: 2740 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "125",
      parent_id: null,
      data: { label: "DynamoDB" },
      position: { x: -145, y: 2779 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "126",
      parent_id: null,
      data: { label: "Document DBs" },
      position: { x: -370, y: 2675 },
      type: "KV",
    },
    {
      id: "127",
      parent_id: null,
      data: { label: "MongoDB" },
      position: { x: -340, y: 2740 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "128",
      parent_id: null,
      data: { label: "CouchDB" },
      position: { x: -340, y: 2779 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "129",
      parent_id: null,
      data: { label: "Realtime" },
      position: { x: -550, y: 2675 },
      type: "KV",
    },
    {
      id: "130",
      parent_id: null,
      data: { label: "Firebase" },
      position: { x: -540, y: 2740 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "131",
      parent_id: null,
      data: { label: "RethinkDB" },
      position: { x: -540, y: 2779 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "132",
      parent_id: null,
      data: { label: "Time Series" },
      position: { x: -750, y: 2675 },
      type: "KV",
    },
    {
      id: "133",
      parent_id: null,
      data: { label: "Influx DB" },
      position: { x: -730, y: 2740 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "134",
      parent_id: null,
      data: { label: "TimeScale" },
      position: { x: -730, y: 2779 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "135",
      parent_id: null,
      data: { label: "Column DBs" },
      position: { x: -950, y: 2675 },
      type: "KV",
    },
    {
      id: "136",
      parent_id: null,
      data: { label: "Cassandra" },
      position: { x: -930, y: 2740 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "137",
      parent_id: null,
      data: { label: "Base" },
      position: { x: -930, y: 2779 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "138",
      parent_id: null,
      data: { label: "Graph DBs" },
      position: { x: -1140, y: 2675 },
      type: "KV",
    },
    {
      id: "139",
      parent_id: null,
      data: { label: "Neo4j" },
      position: { x: -1125, y: 2740 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "140",
      parent_id: null,
      data: { label: "AWS Neptune" },
      position: { x: -1125, y: 2779 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "141",
      parent_id: null,
      data: { label: "Building For Scale" },
      position: { x: -40, y: 3250 },
      type: "BFS",
    },
    {
      id: "142",
      parent_id: null,
      data: { label: "Migration Strategies" },
      position: { x: 200, y: 3262 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "143",
      parent_id: null,
      data: { label: "Migration Strategies" },
      position: { x: 200, y: 2950 },
      type: "MS",
    },
    {
      id: "144",
      parent_id: null,
      data: { label: "Graceful Degradation" },
      position: { x: 213, y: 3010 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "145",
      parent_id: null,
      data: { label: "Throttling" },
      position: { x: 213, y: 3060 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "146",
      parent_id: null,
      data: { label: "Backpressure" },
      position: { x: 213, y: 3110 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "147",
      parent_id: null,
      data: { label: "Loadshifting" },
      position: { x: 213, y: 3160 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "148",
      parent_id: null,
      data: { label: "Circuit Breaker" },
      position: { x: 213, y: 3210 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "149",
      parent_id: null,
      data: { label: "Types of Scaling" },
      position: { x: 200, y: 3302 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "150",
      parent_id: null,
      data: {
        label:
          "Metrics logging and other observable items that can help in debugging and solving Issues when things go wrong.",
      },
      position: { x: 200, y: 3350 },
      type: "MS",
    },
    {
      id: "151",
      parent_id: null,
      data: { label: "Observability" },
      position: { x: 225, y: 3550 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "152",
      parent_id: null,
      data: { label: "Difference & Usage" },
      position: { x: -77, y: 3350 },
      type: "DU",
    },
    {
      id: "153",
      parent_id: null,
      data: { label: "Instrumentation" },
      position: { x: -35, y: 3400 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "154",
      parent_id: null,
      data: { label: "Monitoring" },
      position: { x: -35, y: 3440 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "155",
      parent_id: null,
      data: { label: "Telemetry" },
      position: { x: -35, y: 3480 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Top,
      targetPosition: Position.Top,
    },
    {
      id: "156",
      parent_id: null,
      data: { label: "Basic Infrastructure Knowledge" },
      position: { x: -450, y: 3250 },
      type: "BIK",
    },
  ];

  const edges2 = [
    {
      id: "e1-2",
      source: "1",
      target: "2",
      animated: true,
      type: "smoothstep",
      targetHandle: "top",
    },
    {
      id: "e2-3",
      source: "2",
      target: "3",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e2-4",
      source: "2",
      target: "4",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e2-5",
      source: "2",
      target: "5",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e2-6",
      source: "2",
      target: "6",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e2-7",
      source: "2",
      target: "7",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e2-8",
      source: "2",
      target: "8",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e2-9",
      source: "2",
      target: "9",
      animated: false,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e9-10",
      source: "9",
      target: "10",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e9-20",
      source: "9",
      target: "20",
      animated: false,
      type: "bezier",
      sourceHandle: "bottom",
    },
    {
      id: "e20-21",
      source: "20",
      target: "21",
      animated: true,
      type: "smoothstep",
      sourceHandle: "top",
    },
    {
      id: "e20-22",
      source: "20",
      target: "22",
      animated: false,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e22-23",
      source: "22",
      target: "23",
      animated: true,
      type: "smoothstep",
      sourceHandle: "top",
    },
    {
      id: "e22-25",
      source: "22",
      target: "25",
      animated: true,
      type: "smoothstep",
      sourceHandle: "bottom",
    },
    {
      id: "e22-26",
      source: "22",
      target: "26",
      animated: false,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e26-27",
      source: "26",
      target: "27",
      animated: true,
      type: "smoothstep",
      sourceHandle: "top",
    },
    {
      id: "e26-28",
      source: "26",
      target: "28",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e26-29",
      source: "26",
      target: "29",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e26-30",
      source: "26",
      target: "30",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e26-31",
      source: "26",
      target: "31",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e26-32",
      source: "26",
      target: "32",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e26-33",
      source: "26",
      target: "33",
      animated: false,
      type: "smoothstep",
      sourceHandle: "bottom",
    },
    {
      id: "e33-34",
      source: "33",
      target: "34",
      animated: true,
      type: "straight",
      sourceHandle: "top",
    },
    {
      id: "e33-36",
      source: "33",
      target: "36",
      animated: true,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e33-44",
      source: "33",
      target: "44",
      animated: true,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e33-49",
      source: "33",
      target: "49",
      animated: false,
      type: "straight",
      sourceHandle: "left",
    },
    {
      id: "e49-50",
      source: "49",
      target: "50",
      animated: true,
      type: "straight",
      sourceHandle: "left",
    },
    {
      id: "e50-53",
      source: "50",
      target: "53",
      animated: true,
      type: "straight",
    },
    {
      id: "e49-55",
      source: "49",
      target: "55",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e55-56",
      source: "55",
      target: "56",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e55-57",
      source: "55",
      target: "57",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e55-58",
      source: "55",
      target: "58",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e55-59",
      source: "55",
      target: "59",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e55-60",
      source: "55",
      target: "60",
      animated: false,
      type: "straight",
      sourceHandle: "right",
    },
    {
      id: "e60-61",
      source: "60",
      target: "61",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e60-62",
      source: "60",
      target: "62",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e60-63",
      source: "60",
      target: "63",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e60-64",
      source: "60",
      target: "64",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e64-65",
      source: "64",
      target: "65",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e65-66",
      source: "65",
      target: "66",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-67",
      source: "65",
      target: "67",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-68",
      source: "65",
      target: "68",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-69",
      source: "65",
      target: "69",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-70",
      source: "65",
      target: "70",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-71",
      source: "65",
      target: "71",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-72",
      source: "65",
      target: "72",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e65-73",
      source: "65",
      target: "73",
      animated: true,
      type: "smoothstep",
      sourceHandle: "right",
    },
    {
      id: "e55-74",
      source: "55",
      target: "74",
      animated: true,
      type: "bezier",
      sourceHandle: "bottom",
    },
    {
      id: "e65-82",
      source: "65",
      target: "82",
      animated: false,
      type: "bezier",
      sourceHandle: "bottom",
    },
    {
      id: "e82-83",
      source: "82",
      target: "83",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e82-84",
      source: "82",
      target: "84",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e82-85",
      source: "82",
      target: "85",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e82-86",
      source: "82",
      target: "86",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e82-87",
      source: "82",
      target: "87",
      animated: false,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e87-88",
      source: "87",
      target: "88",
      animated: false,
      type: "straight",
      sourceHandle: "right",
    },
    {
      id: "e88-94",
      source: "88",
      target: "94",
      animated: true,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e87-95",
      source: "87",
      target: "95",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e95-96",
      source: "95",
      target: "96",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e95-97",
      source: "95",
      target: "97",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e95-98",
      source: "95",
      target: "98",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e95-99",
      source: "95",
      target: "99",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e95-100",
      source: "95",
      target: "100",
      animated: true,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e95-101",
      source: "95",
      target: "101",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e101-102",
      source: "101",
      target: "102",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e101-104",
      source: "101",
      target: "104",
      animated: true,
      type: "straight",
      sourceHandle: "left",
    },
    {
      id: "e101-105",
      source: "101",
      target: "105",
      animated: false,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e105-108",
      source: "105",
      target: "108",
      animated: false,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e108-111",
      source: "108",
      target: "111",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e111-112",
      source: "111",
      target: "112",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e111-113",
      source: "111",
      target: "113",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e111-114",
      source: "111",
      target: "114",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e111-115",
      source: "111",
      target: "115",
      animated: true,
      type: "smoothstep",
      sourceHandle: "left",
    },
    {
      id: "e111-116",
      source: "111",
      target: "116",
      animated: false,
      type: "bezier",
      sourceHandle: "bottom",
    },
    {
      id: "e116-117",
      source: "116",
      target: "117",
      animated: true,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e116-118",
      source: "116",
      target: "118",
      animated: true,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e116-119",
      source: "116",
      target: "119",
      animated: true,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e116-120",
      source: "116",
      target: "120",
      animated: true,
      type: "bezier",
      sourceHandle: "right",
    },
    {
      id: "e116-121",
      source: "116",
      target: "121",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e121-122",
      source: "121",
      target: "122",
      animated: false,
      type: "bezier",
      sourceHandle: "left",
    },
    {
      id: "e122-123",
      source: "122",
      target: "123",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e122-126",
      source: "122",
      target: "126",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e122-129",
      source: "122",
      target: "129",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e122-132",
      source: "122",
      target: "132",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e122-135",
      source: "122",
      target: "135",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e122-138",
      source: "122",
      target: "138",
      animated: true,
      type: "bezier",
      sourceHandle: "top",
    },
    {
      id: "e122-141",
      source: "122",
      target: "141",
      animated: false,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e141-142",
      source: "141",
      target: "142",
      animated: true,
      type: "straight",
      sourceHandle: "right",
    },
    {
      id: "e141-152",
      source: "141",
      target: "152",
      animated: true,
      type: "straight",
      sourceHandle: "bottom",
    },
    {
      id: "e141-156",
      source: "141",
      target: "156",
      animated: false,
      type: "straight",
      sourceHandle: "left",
    },
  ];