export   const nodes = [
    {
      id: "1",
      parent_id: null,
      data: { label: "Frontend" },
      position: { x: 218, y: -50 },
      sourcePosition: Position.Bottom,
      targetPosition: Position.Bottom,
    },
    {
      id: "2",
      parent_id: null,
      data: { label: "Internet" },
      position: { x: 242, y: 50 },
      type: "Internet",
    },
    {
      id: "3",
      data: { label: "How does the internet work?" },
      position: { x: 450, y: -40 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "4",
      data: { label: "What is HTTP?" },
      position: { x: 450, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "5",
      data: { label: "What is Domain Name?" },
      position: { x: 450, y: 80 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "6",
      data: { label: "What is hosting?" },
      position: { x: 450, y: 130 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "7",
      data: { label: "DNS and how it works?" },
      position: { x: 450, y: 180 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "8",
      data: { label: "Browsers and how they work?" },
      position: { x: 450, y: 230 },
      style: { background: "#FFEEBA", color: "black" },
      sourcePosition: Position.Left,
      targetPosition: Position.Left,
    },
    {
      id: "9",
      parent_id: null,
      data: { label: "HTML" },
      position: { x: -50, y: 230 },
      type: "HTML",
    },
    {
      id: "10",
      parent_id: null,
      data: { label: "SEO Basics" },
      position: { x: -75, y: 170 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "11",
      parent_id: null,
      data: { label: "Accessibility" },
      position: { x: -75, y: 125 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "12",
      parent_id: null,
      data: { label: "Forms and Validations" },
      position: { x: -75, y: 80 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "13",
      parent_id: null,
      data: { label: "Writing Semantic HTML" },
      position: { x: -75, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "14",
      parent_id: null,
      data: { label: "Learn the basics" },
      position: { x: -75, y: 30 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "15",
      parent_id: null,
      data: { label: "CSS" },
      position: { x: 160, y: 320 },
      type: "CSS",
    },
    {
      id: "16",
      parent_id: null,
      data: { label: "Learn the basics" },
      position: { x: 280, y: 280 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "17",
      parent_id: null,
      data: { label: "Making Layout" },
      position: { x: 280, y: 325 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "18",
      parent_id: null,
      data: { label: "Responsive Design" },
      position: { x: 280, y: 370 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "19",
      parent_id: null,
      data: { label: "JavaScript" },
      position: { x: 138.5, y: 480 },
      type: "JS",
    },
    {
      id: "20",
      parent_id: null,
      data: { label: "Learn the basics" },
      position: { x: -50, y: 440 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "21",
      parent_id: null,
      data: { label: "Learn DOM Manipulation" },
      position: { x: -50, y: 490 },
      style: { background: "#FFEEBA", color: "black", padding: "6px" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "22",
      parent_id: null,
      data: { label: "Fetch API / Ajax (XHR)" },
      position: { x: -50, y: 530 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "23",
      parent_id: null,
      data: { label: "Version Control Systems" },
      position: { x: 370, y: 480 },
      type: "VCS",
    },
    {
      id: "24",
      parent_id: null,
      data: { label: "Git" },
      position: { x: 406.5, y: 580 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "25",
      parent_id: null,
      data: { label: "VCS Hosting" },
      position: { x: 670, y: 480 },
      type: "VCS_Hosting",
    },
    {
      id: "26",
      parent_id: null,
      data: { label: "Bitbucket" },
      position: { x: 667, y: 390 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "27",
      parent_id: null,
      data: { label: "GitLab" },
      position: { x: 667, y: 340 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "28",
      parent_id: null,
      data: { label: "GitHub" },
      position: { x: 667, y: 290 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "29",
      parent_id: null,
      data: { label: "Package Manager" },
      position: { x: 450, y: 700 },
      type: "PM",
    },
    {
      id: "30",
      parent_id: null,
      data: { label: "npm" },
      position: { x: 230, y: 662 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "31",
      parent_id: null,
      data: { label: "pnpm" },
      position: { x: 230, y: 706 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "32",
      parent_id: null,
      data: { label: "yarn" },
      position: { x: 230, y: 750 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "33",
      parent_id: null,
      data: {
        label:
          "We've trimmed down the CSS part for the sake of brevity. You should read about CSS-in-JS, CSS Modules and Styled Components. Alss worth looking at are Pande CSS, Shadcn UI, Mantine and more.",
      },
      position: { x: -120, y: 650 },
      type: "TEXT",
    },
    {
      id: "34",
      parent_id: null,
      data: { label: "Pick a Framework" },
      position: { x: 450.5, y: 896 },
      type: "PaF",
    },
    {
      id: "35",
      parent_id: null,
      data: { label: "React" },
      position: { x: 720, y: 780 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "36",
      parent_id: null,
      data: { label: "Vue.js" },
      position: { x: 720, y: 830 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "37",
      parent_id: null,
      data: { label: "Angular" },
      position: { x: 720, y: 880 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "38",
      parent_id: null,
      data: { label: "Svelte" },
      position: { x: 720, y: 930 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "39",
      parent_id: null,
      data: { label: "Solid.js" },
      position: { x: 720, y: 980 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "40",
      parent_id: null,
      data: { label: "Qwik" },
      position: { x: 720, y: 1030 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "41",
      parent_id: null,
      data: { label: "Writing CSS" },
      position: { x: 101.5, y: 896 },
      type: "WCSS",
    },
    {
      id: "42",
      parent_id: null,
      data: { label: "Tailwind" },
      position: { x: -120, y: 902 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "43",
      parent_id: null,
      data: { label: "CSS Architecture" },
      position: { x: 85, y: 1090 },
      type: "CSSArch",
    },
    {
      id: "44",
      parent_id: null,
      data: { label: "BEM" },
      position: { x: -120, y: 1096 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "45",
      parent_id: null,
      data: { label: "CSS Preprocessors" },
      position: { x: 385, y: 1090 },
      type: "CSSPre",
    },
    {
      id: "46",
      parent_id: null,
      data: { label: "Sass" },
      position: { x: 320, y: 1200 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "47",
      parent_id: null,
      data: { label: "PostCSS" },
      position: { x: 480, y: 1200 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "48",
      parent_id: null,
      data: { label: "Build Tools" },
      position: { x: 750, y: 1360 },
      type: "BTools",
    },
    {
      id: "49",
      parent_id: null,
      data: { label: "Linters and Formatters" },
      position: { x: 400, y: 1320 },
      type: "LaF",
    },
    {
      id: "50",
      parent_id: null,
      data: { label: "Prettier" },
      position: { x: 340, y: 1250 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "51",
      parent_id: null,
      data: { label: "ESLint" },
      position: { x: 510, y: 1250 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "52",
      parent_id: null,
      data: { label: "Module Bundlers" },
      position: { x: 400, y: 1394 },
      type: "ModuleB",
    },
    {
      id: "53",
      parent_id: null,
      data: { label: "Vite" },
      position: { x: 180, y: 1300 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "54",
      parent_id: null,
      data: { label: "esbuild" },
      position: { x: 260, y: 1350 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "55",
      parent_id: null,
      data: { label: "SWC" },
      position: { x: 180, y: 1350 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "56",
      parent_id: null,
      data: { label: "Webpack" },
      position: { x: 180, y: 1400 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "57",
      parent_id: null,
      data: { label: "Rollup" },
      position: { x: 180, y: 1450 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "58",
      parent_id: null,
      data: { label: "Parcel" },
      position: { x: 180, y: 1500 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "59",
      parent_id: null,
      data: { label: "Testing" },
      position: { x: 762, y: 1580 },
      type: "Test",
    },
    {
      id: "60",
      parent_id: null,
      data: { label: "Jest" },
      position: { x: 550, y: 1550 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "61",
      parent_id: null,
      data: { label: "Vitest" },
      position: { x: 398, y: 1550 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "62",
      parent_id: null,
      data: { label: "Playwright" },
      position: { x: 743, y: 1680 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "63",
      parent_id: null,
      data: { label: "Cypress" },
      position: { x: 743, y: 1722 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "64",
      parent_id: null,
      data: { label: "Authentication Strategies" },
      position: { x: 300, y: 1680 },
      type: "Auth",
    },
    {
      id: "65",
      parent_id: null,
      data: { label: "Web Security Basics" },
      position: { x: -80, y: 1620 },
      type: "WSB",
    },
    {
      id: "66",
      parent_id: null,
      data: { label: "OWASP Security Risks" },
      position: { x: -58, y: 1500 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "67",
      parent_id: null,
      data: { label: "Content Security Policy" },
      position: { x: -58, y: 1455 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "68",
      parent_id: null,
      data: { label: "CORS" },
      position: { x: -58, y: 1410 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "69",
      parent_id: null,
      data: { label: "HTTPS" },
      position: { x: 22, y: 1410 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "70",
      parent_id: null,
      data: { label: "Web Components" },
      position: { x: -73, y: 1850 },
      type: "WebC",
    },
    {
      id: "71",
      parent_id: null,
      data: { label: "HTML Templates" },
      position: { x: -58, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "72",
      parent_id: null,
      data: { label: "Custom Elements" },
      position: { x: -58, y: 2000 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "73",
      parent_id: null,
      data: { label: "Shadow DOM" },
      position: { x: -58, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "74",
      parent_id: null,
      data: { label: "Type Checkers" },
      position: { x: 250, y: 1850 },
      type: "TypeC",
    },
    {
      id: "75",
      parent_id: null,
      data: { label: "TypeScript" },
      position: { x: 254, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "76",
      parent_id: null,
      data: { label: "SSR" },
      position: { x: 500, y: 2020 },
      type: "SSR",
    },
    {
      id: "77",
      parent_id: null,
      data: { label: "React" },
      position: { x: 680, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Right,
    },
    {
      id: "78",
      parent_id: null,
      data: { label: "Next.js" },
      position: { x: 880, y: 1900 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "79",
      parent_id: null,
      data: { label: "Astro" },
      position: { x: 880, y: 1950 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "80",
      parent_id: null,
      data: { label: "react-router" },
      position: { x: 880, y: 2000 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "81",
      parent_id: null,
      data: { label: "Angular" },
      position: { x: 680, y: 2000 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "82",
      parent_id: null,
      data: { label: "Vue.js" },
      position: { x: 680, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Right,
    },
    {
      id: "83",
      parent_id: null,
      data: { label: "Nuxt.js" },
      position: { x: 860, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "84",
      parent_id: null,
      data: { label: "Svelte" },
      position: { x: 680, y: 2100 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Right,
    },
    {
      id: "85",
      parent_id: null,
      data: { label: "Svelte Kit" },
      position: { x: 860, y: 2100 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Left,
      sourcePosition: Position.Left,
    },
    {
      id: "86",
      parent_id: null,
      data: { label: "GraphQL" },
      position: { x: 251, y: 2200 },
      type: "GraphQL",
    },
    {
      id: "87",
      parent_id: null,
      data: { label: "Relay Modern" },
      position: { x: 237, y: 2100 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "88",
      parent_id: null,
      data: { label: "Apollo" },
      position: { x: 237, y: 2050 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "89",
      parent_id: null,
      data: { label: "PWAs" },
      position: { x: 261, y: 2360 },
      type: "PWAs",
    },
    {
      id: "90",
      parent_id: null,
      data: { label: "box" },
      position: { x: 0, y: 2120 },
      type: "box",
    },
    {
      id: "91",
      parent_id: null,
      data: { label: "Using DevTools" },
      position: { x: 10, y: 2340 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "92",
      parent_id: null,
      data: { label: "Using Lighthouse" },
      position: { x: 10, y: 2290 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "93",
      parent_id: null,
      data: { label: "Performance Metrics" },
      position: { x: 10, y: 2240 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "94",
      parent_id: null,
      data: { label: "RAIL Model" },
      position: { x: 10, y: 2190 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "95",
      parent_id: null,
      data: { label: "PRPL Pattern" },
      position: { x: 10, y: 2140 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "96",
      parent_id: null,
      data: { label: "box2" },
      position: { x: 0, y: 2455 },
      type: "box2",
    },
    {
      id: "97",
      parent_id: null,
      data: { label: "Credentials" },
      position: { x: 10, y: 2875 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "98",
      parent_id: null,
      data: { label: "Payments" },
      position: { x: 10, y: 2825 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "99",
      parent_id: null,
      data: { label: "Device Orientation" },
      position: { x: 10, y: 2775 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "100",
      parent_id: null,
      data: { label: "Notifications" },
      position: { x: 10, y: 2725 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "101",
      parent_id: null,
      data: { label: "Location" },
      position: { x: 10, y: 2675 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "102",
      parent_id: null,
      data: { label: "Service Workers" },
      position: { x: 10, y: 2625 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "103",
      parent_id: null,
      data: { label: "Server Sent Events" },
      position: { x: 10, y: 2575 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "104",
      parent_id: null,
      data: { label: "Web Socket" },
      position: { x: 10, y: 2525 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "105",
      parent_id: null,
      data: { label: "Storage" },
      position: { x: 10, y: 2475 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "106",
      parent_id: null,
      data: { label: "Performance Best Practices" },
      position: { x: 240, y: 2500 },
      type: "PBP",
    },
    {
      id: "107",
      parent_id: null,
      data: { label: "Static Site Generators" },
      position: { x: 560, y: 2360 },
      type: "SSG",
    },
    {
      id: "108",
      parent_id: null,
      data: { label: "Eleventy" },
      position: { x: 588, y: 2270 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "109",
      parent_id: null,
      data: { label: "Vuepress" },
      position: { x: 588, y: 2220 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "110",
      parent_id: null,
      data: { label: "Next.js" },
      position: { x: 588, y: 2170 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "111",
      parent_id: null,
      data: { label: "Astro" },
      position: { x: 668, y: 2170 },
      style: { background: "#FFEEBA", color: "black", width: "70px" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "112",
      parent_id: null,
      data: { label: "Nuxt.js" },
      position: { x: 588, y: 2480 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Top,
      sourcePosition: Position.Top,
    },
    {
      id: "113",
      parent_id: null,
      data: { label: "Mobile Apps" },
      position: { x: 880, y: 2360 },
      type: "Mobile",
    },
    {
      id: "114",
      parent_id: null,
      data: { label: "Ionic" },
      position: { x: 877, y: 2270 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "115",
      parent_id: null,
      data: { label: "Flutter" },
      position: { x: 877, y: 2220 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "116",
      parent_id: null,
      data: { label: "React Native" },
      position: { x: 877, y: 2170 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Bottom,
      sourcePosition: Position.Bottom,
    },
    {
      id: "117",
      parent_id: null,
      data: { label: "Desktop Apps" },
      position: { x: 580, y: 2650 },
      type: "Desktop",
    },
    {
      id: "118",
      parent_id: null,
      data: { label: "Electron" },
      position: { x: 380, y: 2605 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "119",
      parent_id: null,
      data: { label: "Tauri" },
      position: { x: 380, y: 2655 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
    {
      id: "120",
      parent_id: null,
      data: { label: "Flutter" },
      position: { x: 380, y: 2705 },
      style: { background: "#FFEEBA", color: "black" },
      targetPosition: Position.Right,
      sourcePosition: Position.Right,
    },
  ];

export const edges = [
  {
    id: "e1-2",
    source: "1",
    target: "2",
    animated: true,
    type: "smoothstep",
    targetHandle: "top",
  },
  {
    id: "e2-3",
    source: "2",
    target: "3",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-6",
    source: "2",
    target: "6",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-7",
    source: "2",
    target: "7",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-8",
    source: "2",
    target: "8",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e2-9",
    source: "2",
    target: "9",
    type: "bezier",
  },
  {
    id: "e2-10",
    source: "9",
    target: "10",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-11",
    source: "9",
    target: "11",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-12",
    source: "9",
    target: "12",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-13",
    source: "9",
    target: "13",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e2-14",
    source: "9",
    target: "14",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "e9-15",
    source: "9",
    target: "15",
    type: "bezier",
    sourceHandle: "right2",
    targetHandle: "left",
  },
  {
    id: "e15-16",
    source: "15",
    target: "16",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "e15-17",
    source: "15",
    target: "17",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "e15-18",
    source: "15",
    target: "18",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "e15-19",
    source: "15",
    target: "19",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "e19-20",
    source: "19",
    target: "20",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "e19-21",
    source: "19",
    target: "21",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "e19-22",
    source: "19",
    target: "22",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "e19-23",
    source: "19",
    target: "23",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "e23-24",
    source: "23",
    target: "24",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "e23-25",
    source: "23",
    target: "25",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "25-26",
    source: "25",
    target: "26",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "25-27",
    source: "25",
    target: "27",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "25-28",
    source: "25",
    target: "28",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "25-29",
    source: "25",
    target: "29",
    animated: false,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "29-30",
    source: "29",
    target: "30",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "29-31",
    source: "29",
    target: "31",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "29-32",
    source: "29",
    target: "32",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "29-34",
    source: "29",
    target: "34",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "34-35",
    source: "34",
    target: "35",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-36",
    source: "34",
    target: "36",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-37",
    source: "34",
    target: "37",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-38",
    source: "34",
    target: "38",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-39",
    source: "34",
    target: "39",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-40",
    source: "34",
    target: "40",
    animated: true,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "34-41",
    source: "34",
    target: "41",
    animated: false,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "41-42",
    source: "41",
    target: "42",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "41-43",
    source: "41",
    target: "43",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "43-44",
    source: "43",
    target: "44",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "43-45",
    source: "43",
    target: "45",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "45-46",
    source: "45",
    target: "46",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "45-47",
    source: "45",
    target: "47",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom2",
  },
  {
    id: "45-48",
    source: "45",
    target: "48",
    animated: false,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "48-49",
    source: "48",
    target: "49",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "49-50",
    source: "49",
    target: "50",
    animated: true,
    type: "bezier",
    sourceHandle: "top",
  },
  {
    id: "49-51",
    source: "49",
    target: "51",
    animated: true,
    type: "bezier",
    sourceHandle: "top2",
  },
  {
    id: "48-52",
    source: "48",
    target: "52",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "52-53",
    source: "52",
    target: "53",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-54",
    source: "52",
    target: "54",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-56",
    source: "52",
    target: "56",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-57",
    source: "52",
    target: "57",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "52-58",
    source: "52",
    target: "58",
    animated: true,
    type: "smoothstep",
    sourceHandle: "left",
  },
  {
    id: "48-59",
    source: "48",
    target: "59",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "59-60",
    source: "59",
    target: "60",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "59-63",
    source: "59",
    target: "63",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "59-64",
    source: "59",
    target: "64",
    animated: false,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "64-65",
    source: "64",
    target: "65",
    animated: false,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "65-66",
    source: "65",
    target: "66",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "65-67",
    source: "65",
    target: "67",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "65-70",
    source: "65",
    target: "70",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "70-73",
    source: "70",
    target: "73",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "70-74",
    source: "70",
    target: "74",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "74-75",
    source: "74",
    target: "75",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "74-76",
    source: "74",
    target: "76",
    animated: false,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "76-77",
    source: "76",
    target: "77",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "77-78",
    source: "77",
    target: "78",
    animated: true,
    type: "bezier",
  },
  {
    id: "77-79",
    source: "77",
    target: "79",
    animated: true,
    type: "bezier",
  },
  {
    id: "77-80",
    source: "77",
    target: "80",
    animated: true,
    type: "bezier",
  },
  {
    id: "76-81",
    source: "76",
    target: "81",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "76-82",
    source: "76",
    target: "82",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "82-83",
    source: "82",
    target: "83",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "76-84",
    source: "76",
    target: "84",
    animated: true,
    type: "bezier",
    sourceHandle: "right",
  },
  {
    id: "84-85",
    source: "84",
    target: "85",
    animated: true,
    type: "smoothstep",
  },
  {
    id: "76-86",
    source: "76",
    target: "86",
    animated: false,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "86-88",
    source: "86",
    target: "88",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "86-89",
    source: "86",
    target: "89",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "89-90",
    source: "89",
    target: "90",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "89-96",
    source: "89",
    target: "96",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "89-106",
    source: "89",
    target: "106",
    animated: true,
    type: "bezier",
    sourceHandle: "bottom",
  },
  {
    id: "89-107",
    source: "89",
    target: "107",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "107-108",
    source: "107",
    target: "108",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "107-112",
    source: "107",
    target: "112",
    animated: true,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "107-113",
    source: "107",
    target: "113",
    animated: false,
    type: "smoothstep",
    sourceHandle: "right",
  },
  {
    id: "113-116",
    source: "113",
    target: "116",
    animated: true,
    type: "smoothstep",
    sourceHandle: "top",
  },
  {
    id: "113-117",
    source: "113",
    target: "117",
    animated: false,
    type: "smoothstep",
    sourceHandle: "bottom",
  },
  {
    id: "117-118",
    source: "117",
    target: "118",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "117-119",
    source: "117",
    target: "119",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
  {
    id: "117-120",
    source: "117",
    target: "120",
    animated: true,
    type: "bezier",
    sourceHandle: "left",
  },
];
